### ISSUE TITLE
Is dialect.caseSensitiveHeader supported for validation?

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/datapackage-js#101]
I can see the default dialect sets caseSensitiveHeader to false.
How do I/can I use it to validate a data resource that had headers, say, like:
`h1, H1`

**Comment by roll** [comment]
No, it's not supported:
> name SHOULD NOT be considered case sensitive in determining uniqueness. However, since it should correspond to the name of the field in the data file it may be important to preserve case.
