### ISSUE TITLE
EscapeChar and QuoteChar

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/datapackage-js#102]
[https://frictionlessdata.io/specs/csv-dialect/#specification](https://frictionlessdata.io/specs/csv-dialect/#specification)
says that escapeChar and quoteChar should be mutually exclusive.
When we call Resource.commit(), we see both in the dialect returned. Should only 1 of them be there?

**Comment by roll** [comment]
@mattRedBox 
Yes only 1

I think it's already fixed in PY:
- https://github.com/frictionlessdata/datapackage-js/blob/master/src/config.js#L15-L16
- https://github.com/frictionlessdata/datapackage-py/commit/7b4f248022adcbf19487bd33931555b624996250#diff-dba68baa155411783caee008a505a0e0
