### ISSUE TITLE
Implementing foreign keys using remote package json

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/datapackage-js#103]
Hi @Stephen-Gates , @roll 
Just opening this to make sure I understand the implementation requirements for doing PR for this.
To validate a foreign key that has a package URL, noting @roll your comments about [place](https://github.com/frictionlessdata/datapackage-js/blob/master/src/resource.js#L396):
and 
`integrity check + dereferencing`
The PR then should include:
- loading package URL
- checking loaded package is valid
- ensuring that resource and fields outlined in the relevant foreign key are present in the loaded package

Is this correct - is there anything else I need to include?

**Comment by roll** [comment]
I'm a little bit out of context for now but I guess the main approach I was thinking about - to get a `Resource ` instance from a referenced data package (in the `_getRelations` function). 

That's the only thing that should differ (be extended) compared to the current state. When we get the `Resource` instance all other code will just work.

**Comment by Stephen-Gates** [comment]
Some context... 

In [Data Curator](https://github.com/ODIQueensland/data-curator) we're implementing the [Foreign Keys to Data Packages](https://frictionlessdata.io/specs/patterns/#table-schema:-foreign-keys-to-data-packages) pattern.

<img width="924" alt="screenshot 2018-04-28 09 26 52" src="https://user-images.githubusercontent.com/9379524/39388836-6a779bd2-4ac6-11e8-8c1b-9c1b15d6c622.png">

As [previously agreed](https://gitter.im/frictionlessdata/chat?at=5ad6b53701a2b40f382edca2), we're using `package` not `datapackage` in the pattern and are waiting on https://github.com/frictionlessdata/specs/pull/611 to be merged. Then we'll merge the associated change to the test data, https://github.com/frictionlessdata/example-data-packages/pull/53.

This change is to add Foreign Keys to Data Packages pattern support to datapackage.js.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
I've got some questions to raise in our own code, as I'm not clear now as to why we need datapackage-js in the code highlighted - it seems at odds with what we use in Data Curator for validation.

**Comment by mattRedBox** [comment]
@Stephen-Gates 
Don't think, at this stage anyway, we need to do anything with relations other than what is already present.
