### ISSUE TITLE
Latest profile update causes validation of resource erroring at dialect/description

### ISSUE THREAD

**Issue by ghost** [frictionlessdata/datapackage-js#105]
Hi @roll 
With the profile update required before last release, we now receive a validation error for dialect in Data-Curator
`Descriptor validation error: Missing required property: description at "/dialect" in descriptor and at "/properties/dialect/required/0" in profile`

I suspect this is due to the [profile update](https://github.com/frictionlessdata/datapackage-js/commit/bdce391a5dd09313be2a484b609a9b882906e85b#diff-265eef5c29ae53ed44cfeff311b25383L2005) reflected in spec here:

``` "dialect": {
     ...
      "required": [
        "description"
      ],
      "properties": {
        "description": {
          "required": [
            "delimiter",
            "doubleQuote"
          ],
```

Sorry for missing this, but I'm not sure what this means: 
- is the spec correct? (I'm guessing it is) or, 
- should dialect now have a 'description' property which now references all of the former dialect attributes?
There will be some upcoming support work for Data-Curator soon, so please let me know if you require a PR request for this, and I can then advise of a timeline for you.

**Comment by roll** [comment]
@mattRedBox 
TBH I'm not sure why this change has happened - https://github.com/frictionlessdata/specs/commit/b5a8daf68584088408d29ee4251176cc800e9b89 - and what is a `description` field.

http://frictionlessdata.io/specs/csv-dialect/

**Comment by mattRedBox** [comment]
Thanks for raising this @roll

**Comment by roll** [comment]
@mattRedBox 
For now, I've released both py/js libs with rolled profiles back.
