### ISSUE TITLE
Three package tests fail - descriptor url isn't working

### ISSUE THREAD

**Issue by kleanthisk10** [frictionlessdata/datapackage-js#107]
These tests seem to have problem:

- [loads resource from absolute URL](https://github.com/frictionlessdata/datapackage-js/blob/7726f6738dccaaf56fbf3a3cd30f1859304017c4/test/package.js#L62)
- [loads resource from absolute URL disregarding basePath](https://github.com/frictionlessdata/datapackage-js/blob/7726f6738dccaaf56fbf3a3cd30f1859304017c4/test/package.js#L75)
- [loads remote resource with basePath](https://github.com/frictionlessdata/datapackage-js/blob/7726f6738dccaaf56fbf3a3cd30f1859304017c4/test/package.js#L88)

The following url isn't working:
https://dev.keitaro.info/dpkjs/datapackage.json

**Comment by roll** [comment]
@kleanthisk10 
Thanks. Should be fine now

**Comment by kleanthisk10** [comment]
@roll url still isn't working!

**Comment by roll** [comment]
@kleanthisk10 
We have no control over that server. So I've replaced it with the correct link in the master.
