### ISSUE TITLE
Example for usage in browser

### ISSUE THREAD

**Issue by samuelmr** [frictionlessdata/datapackage-js#112]
# Overview

The README shows one can load datapackage.js from a CDN:
```html
<script src="//unpkg.com/datapackage/dist/datapackage.min.js"></script>
```

The following examples don't work in the browser since they use ```require()``` which is not supported by browsers.

It would be nice to have (e.g. in the examples folder) a complete HTML page demonstrating the usage in browser.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @samuelmr,

I've added an example - https://github.com/frictionlessdata/datapackage-js#browser

It's built using `webpack` so it works in browsers also.
