### ISSUE TITLE
Resources base path

### ISSUE THREAD

**Issue by dumyan** [frictionlessdata/datapackage-js#26]
Currently resources path is handled from the current working directory (where the library is initialized). 

One obvious problem with this is that it makes it impossible to load datapackage resources when starting the library from a different directory then the datapackage itself,  and then loading the datapackage descriptor from a file (the descriptor points to the resources relative to its directory and the library tries to open them relative to the working directory).

**Comment by roll** [comment]
@dumyan 
So we could add `basePath` to `DataPackage` and `Resource` like in python library. WDYT?
