### ISSUE TITLE
Package name for npm

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/datapackage-js#3]
`dpm` currently uses `datapackage` (`dpm` was unfortunately already taken).

My suggestion would be to have `dpm` move to `datapackagemanager` or something (sort of ugly but hey) and have this lib take over for `datapackage` in npm.

Alternatives are using datapkg but that is pretty confusing (having datapkg and datapackage)

---

requires frictionlessdata/dpm#58

**Comment by pwalsh** [comment]
@rgrp ok. `datapackagemanager` seems long though. Would `datapackage-cli`, or `dpm-js` be options? Otherwise, let's go with `datapackagemanager`

**Comment by rgrp** [comment]
@pwalsh dpm-js could be possible - it is just a bit weird for npm as it is obviously js stuff. What would you vote between:

`datapackagemanager` and `dpm-js`

**Comment by pwalsh** [comment]
I think `datapackagemanager` actually.

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/dpm/issues/58

**Comment by rgrp** [comment]
@roll i am little unclear why you close this issue in favour or another issue which is identical ;-)

I ask as someone closely watching the repo and trying to track what is going on ;-)

If you are going to MOVE maybe make clear why you are when closing. Alternatively could we not just rename this issue to indicate that we have now decided to action this (I assume the reason you opened a new issue was to indicate move from discussion to a decision ...)

**Comment by roll** [comment]
@rgrp 
I've assumed you've got a decision here. Don't you?

**Comment by rgrp** [comment]
@pwalsh we did have a decision - that was my point. So why not just use this issue on an ongoing basis ;-) (this is minor procedural point about making it easy for people to follow what is happening).

@roll do we really want a straight port - and could we have a bit of a roadmap on API and a very clear upstream use so we dogfood as we go

**Comment by roll** [comment]
OK, let's work with this issue. For me just more usual approach when discussion/question is resolved to close the issue and to open an issue with specified task (I've forgot to add link to the discussion my bad). Anyway pretty minor thing - ok with either)

**Comment by roll** [comment]
@pwalsh 
@rufuspollock 
So we're almost ready to publish.

**Comment by roll** [comment]
DONE
https://www.npmjs.com/package/datapackage
