### ISSUE TITLE
Fix build process for registry.csv

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#37]
# Overview

For now `webpack` skip `registry.csv` so we're getting broken build.

# Tasks

- [ ] rebase on `profiles.json` (`registry.json`) OR
- [ ] use `url-loader` for `csv` in webpack

**Comment by roll** [comment]
@pwalsh 
could we rebase on `profiles.json` (in https://github.com/frictionlessdata/schemas)?

**Comment by pwalsh** [comment]
@roll yes: `registry.json`
