### ISSUE TITLE
Relative paths in remote datapackages don't work

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#41]
# Overview

```javascript
const Datapackage = require('datapackage-test').Datapackage
const descriptor = 'https://raw.githubusercontent.com/frictionlessdata/datapackage-js/master/data/dp1/datapackage.json'

new Datapackage(descriptor).then(dp => {
    dp.resources[0].table.then(table => console.log(table.read()))
})
```

```
Error: ENOENT: no such file or directory, open 'data.csv'
```

# Tasks

- [ ] fix broken behavior
- [ ] add tests

**Comment by rufuspollock** [comment]
@roll any update on a fix here (or confirmation this is a bug)? I'd like to use this feature in DPR if we can ...

**Comment by roll** [comment]
@rufuspollock 
It's confirmed - we're starting to work on it.

**Comment by dumyan** [comment]
@roll 

this should be fixed in `jsontableschema-js`, because we're just wrapping the `Table` class here. Basically when doing `table.read()` you are using only `jsontableschema-js` code.

Therefore, the estimate is for `jsontableschema-js`.

**Comment by roll** [comment]
I suppose error could be in code where we pass `path` to `jsontableschema.Table`
