### ISSUE TITLE
Consider renaming async Resource.table to async Resource.getTable()

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#42]
# Overview

For now async getter could be confusing:
```javascript
const table = await dp.resources[0].table
```
to
```javascript
const table = await dp.resources[0].getTable()
```
But it should discussed first because option 1 is closer to Python version.

# Tasks

- [ ] sync with @roll
- [ ] add not to readme about breaking changes

**Comment by rufuspollock** [comment]
@roll my 2c is the `.table` stuff is nicer and one can just accept this stuff is all async and liberally sprinkle `await` in client codebases ...

**Comment by roll** [comment]
WONTFIX
