### ISSUE TITLE
Option to load table data without casting the data

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/datapackage-js#51]
Often I just want the data from a CSV file parsed but not cast - is there an option to do this.

Generally I flag an issue re parsing fields that are dates - often i want the original date structure without it being parsed to dates. (I can explain better if this is not clear).

**Comment by roll** [comment]
@rufuspollock 
Thanks, it's clear.

**Comment by rufuspollock** [comment]
I think this is also useful to get the data without running into validation problems (does JTS validate before casting?)

**Comment by roll** [comment]
Yes. So I've merged this two. JTS casts data and validates it based on casting results (so it's the same process).

**Comment by roll** [comment]
WILL BE IMPLEMENTED in https://github.com/frictionlessdata/tableschema-js/issues/68
