### ISSUE TITLE
Issue with co2-pmm datapackage with raiseInvalid is false

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#53]
# Overview

https://raw.githubusercontent.com/frictionlessdata/dpr-js/gh-pages/fixtures/dp3/datapackage.json

> I am getting Wrong type for header error even if I set raiseInvalid to false.

**Comment by roll** [comment]
@dumyan 
I had no time to analyze it. Please take a look and estimate when you'll be having time.

**Comment by dumyan** [comment]
@roll

this question is related to `jts.Table`. The datapackage doesn't contain any errors and the `Wrong type for header` error is shown when using `table.read` and `table.iter`.

**Comment by roll** [comment]
@dumyan 
Thanks. I'll investigate it on table schema level on the next iteration.
