### ISSUE TITLE
Need to change http to https or disable it

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/datapackage-js#54]
At the moment, we are getting error because of `http` request instead of `https` when requesting `http://schemas.datapackages.org/registry.json`:

Mixed Content: The page was loaded over HTTPS, but requested an insecure resource 'http://schemas.datapackages.org/registry.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by anuveyatsu** [comment]
At the moment, `datapackage-test` library uses data from following source: http://schemas.datapackages.org/registry.json

And in this source, there are 3 schema paths, which have `http` URLs.

Also, when we try manually change `http` to `https`, there is certificate problems on https://schemas.datapackages.org/registry.json

**Comment by roll** [comment]
Thanks!

@dumyan 
Registry https: https://schemas.frictionlessdata.io/registry.csv

**Comment by pwalsh** [comment]
@roll should just be able to do references as `//schemas.frictionlessdata.io/registry.csv` from now on.

**Comment by roll** [comment]
Will be resolved by https://github.com/frictionlessdata/schemas/pull/67 (I will update builtin datapackage schemas)

**Comment by roll** [comment]
FIXED in 0397fb83b0841fb2b85b51ce6f3f78b32bffa368
