### ISSUE TITLE
Investigate idea of TabularResource.js (combination of Resource.js and Table.js)?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#59]
@rufuspollock:

>  i wondered if you had seen https://github.com/rufuspollock/dataframe.js - more discussion than code.
>
> Particularly, wondering with connections with Resources.js / Table.js stuff in https://github.com/frictionlessdata/jsontableschema-js + https://github.com/frictionlessdata/datapackage-js#resource.
>
> It seems to me that the Table.js could basically extend to this [i.e. dataframe / TabularResource) - or we could provide some wrappers … (i don’t know how well you know dataframe stuff in pandas http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dataframe)
>
> There is a some summary of dataframe libs in the README here https://github.com/rufuspollock/dataframe.js

**Comment by rufuspollock** [comment]
@roll i've renmaed it a bit to reflect the point. Basically, Table.js duplicates from of the stuff from a Tabular Resource.js. Are there ways to merge them and make an awesome TabularResource - that is developing in the direction of a proper DataFrame object ...

**Comment by roll** [comment]
@rufuspollock 
Resource and Table is just an implementations of specs. My first try was to have TabularResource but it just hadn't work with all requirements from 2 different specs, sql/bigquery/etc integrations etc.

So if we need to have DataFrame object we just should wrap existent Resource/Table API to provide needed high-level API. An attempt to have 1 API (class) to conform 3 different requirements (table schema spec, tabular resource spec and data frame) will probably fail I suppose. 

But I still have to dive in your research)

**Comment by rufuspollock** [comment]
@roll let's distinguish:

- TabularResource object
- Full on DataFrame (more work)

Focus for now is the first item.

**Comment by roll** [comment]
FIXED/WONTFIX

In `v1` release `Resource` provides both non-tabular and tabular interfaces. :

```javascript
resource = await Resource.load('data.csv')
resource.read() // bytes
if (resource.tabular) {
  resource.table.read() // rows
}
```

Link to an alternative implementation `data.js`:
- https://github.com/datahq/data.js#datajs
