### ISSUE TITLE
React Component for a data resource

### ISSUE THREAD

**Issue by rgbkrk** [frictionlessdata/datapackage-js#65]
Has anyone made a React Component that accepts dataresource json?

**Comment by pwalsh** [comment]
@rufuspollock are the react components in https://github.com/frictionlessdata/dpr-js clean/extractable for standalone use?

**Comment by rufuspollock** [comment]
@rgbkrk great question 😄 

@rgbkrk @pwalsh I'm actually working on that 😄 - the current code is pretty close but would probably need a bit of tweaking. The relevant component is this container:

https://github.com/frictionlessdata/dpr-js/blob/gh-pages/src/containers/DataPackageView.jsx

Basically you pass it a Data Package (not a resource but that is trivial to change) and it then renders tables for each resource in the Data Package plus the views. You can see the kind of output (in progress and not yet launched) here: https://staging.datapackaged.com/core/finance-vix

@rgbkrk what is your exact use case? That would help in providing guidance.

**Comment by rgbkrk** [comment]
Within the Jupyter ecosystem, we'd like to be able to allow libraries to provide `application/vnd.dataresource+json`. Pandas recently merged a PR to provide a default representation of a DataFrame as a data resource json when an optional flag is set: https://github.com/pandas-dev/pandas/pull/14904

The way that the nteract notebook works (same protocol as Jupyter) is that it takes a payload like:

```json
{
  "text/html": "...some HTML",
  "application/vnd.dataresource+json": { "schema": {}, "data": [] }
}
```

picks the "richest" of the media types and passes the data into a React component to render it. As an example, here's me working with baseball data in pandas:

![screen shot 2017-03-04 at 11 05 58 am](https://cloud.githubusercontent.com/assets/836375/23581575/40a1d5e8-00cb-11e7-88e7-7f1dc07c875b.png)

That's the `text/html` version provided by pandas, which could instead be a rendered version of the data resource, which is now part of the payload for dataframe representation:

![screen shot 2017-03-04 at 11 11 36 am](https://cloud.githubusercontent.com/assets/836375/23581581/59588104-00cb-11e7-8243-e4ba1884470f.png)

**Comment by rufuspollock** [comment]
@rgbkrk great, much clearer now on the use case. Would it be possible to arrange a short chat or call to talk further with myself or @pwalsh? Easiest way is to ping me us on gitter via the FrictionlessData channel https://gitter.im/frictionlessdata/chat

**Comment by rgbkrk** [comment]
Sure, I'm happy to have a chat/call. We've also done some preliminary work to explore the space here: https://github.com/nteract/nteract/pull/1534

**Comment by rufuspollock** [comment]
@rgbkrk great! Can you PM me on gitter -- i'm rufuspollock. Alternatively, let me know how to ping you.

**Comment by pwalsh** [comment]
@rgbkrk how did things develop here?

**Comment by rgbkrk** [comment]
We brought it in and the data resource spec [has been part of the nteract release line since August](https://twitter.com/rgbkrk/status/898700422726041600). Feel free to [try it out](https://github.com/nteract/nteract/releases/latest)!

The community has also been picking it up as the table schema support that pandas introduced is now used by [qgrid](https://github.com/quantopian/qgrid) to create dynamic tables that rely on table schema.

**Comment by pwalsh** [comment]
@rgbkrk that is amazing! I'll close this issue then. 

I'll talk to @callmealien and @jobarratt here at OKI about a short write up on this work - is it ok if they reach out to you?
