### ISSUE TITLE
Resource property "path: <path>" is deprecated

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/datapackage-js#78]
I am getting following error for data packages with resource path as a string (`"path": "data/resource.csv"`):

```
Resource property "path: <path>" is deprecated.
           Please use "path: [path]" instead (as array).
```

Was it decided to specify resource path as an array only or is it still under discussion?

**Comment by roll** [comment]
It's an implementation based on unofficial `specs-v1.0-rc.2` revision. And final revision has returned support for `path: <string>`. We will update it after specs v1 release. I suppose for now it just logs warnings not errors.
