### ISSUE TITLE
Rename DataPackage to Package

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/datapackage-js#81]
As class names shouldn't we have

EITHER Package and Resource

OR DataPackage and DataResource

At the moment we DataPackage and Resource.

**Comment by roll** [comment]
Ruby implementations has `Package`
cc @pwalsh @akariv @amercader

**Comment by rufuspollock** [comment]
I'd vote for Package and Resource.

**Comment by pwalsh** [comment]
It is just historical. `Data Resource` only really became a fully formed concept in recent months. I think we should be consistent `Package` / `Resource` or `DataPackage` / `DataResource`, but I am not opinionated on which one. Whatever @roll decides.

**Comment by roll** [comment]
`Package` and `Resource` sounds great. It was little bit confusing to have `datapackage` module, `DataPackage` class and `data_package` (explicit `dp`) instance in documentation.

**Comment by rufuspollock** [comment]
@roll I agree!
