### ISSUE TITLE
Required property "uri" in licenses and sources

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/datapackage-js#83]
Validation is not passing due to missing `uri` property in `licenses` and `sources`. Is that expected? I've looked at https://specs.frictionlessdata.io/data-package/#licenses and https://specs.frictionlessdata.io/data-package/#sources and it seems like it does not have `uri` property at all (and also all properties are optional). However, in the default profile here it says it is required - https://github.com/frictionlessdata/datapackage-js/blob/master/src/profiles/data-package.json#L197

**Comment by roll** [comment]
@anuveyatsu 
Is it `alpha` version? I think there is still specs problems but have you tried to use `new DataPackage(descriptor, {strict: false})`? to do not trow on validation errors?
