### ISSUE TITLE
Support csv dialects

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#86]
# Overview

For now csv dialects from resource descriptor is ignored. It should be implemented on `tableschema.Table` level first.

# Plan

- [x] implement on `tableschema` level - https://github.com/frictionlessdata/tableschema-js/pull/96
- [ ] map resource's `descriptor.dialect` to `Table.load(...parserOptions)` 
- [ ] add CSV Dialect tests
- [ ] pass `encoding/format` to `tableschema.Table`

**Comment by rufuspollock** [comment]
Note a bunch of this is implemented in data.js. I cannot stress how valuable it would be to have a call before we all do further work ... /cc @pwalsh

**Comment by rufuspollock** [comment]
@roll ditto my comment here /cc @vitorbaptista

**Comment by vitorbaptista** [comment]
@rufuspollock @roll is off this week, but I pinged him for us to talk about data.js
