### ISSUE TITLE
Improve validation for data package descriptor properties

### ISSUE THREAD

**Issue by mattRedBox** [frictionlessdata/datapackage-js#96]
Hi
Not sure if I missed it in the library, but when adding non-required properties,
http://frictionlessdata.io/specs/data-package/#required-properties,
 such as:
- id
- title
- description
- version
- sources
- licenses

it did not seem that the package descriptor validated these (e.g., version). I can see these fields (and any others I create) added to the datapackage descriptor (if I'm putting these in the right place?), but they do not seem to have any validation against them. Please let me know what I might have missed, or  could validation of these properties be considered in a future release? @Stephen-Gates, thoughts?

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox 

Are you saying that only the existence of at least one resource is tested and other items aren't?

Without looking at the code, I'd like to think that checks like the following are done:

-  "[`name`](http://frictionlessdata.io/specs/data-package/#name) MUST be lower-case and contain only alphanumeric characters along with ".", "_" or "-" characters".
- the [`licenses`](http://frictionlessdata.io/specs/data-package/#licenses) `name`  MUST be an Open Definition license ID
- the [`description`](http://frictionlessdata.io/specs/data-package/#description) MUST be markdown formatted
- etc.

If that's the case, then I agree with your feature request.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Sorry a little overzealous in vomiting up properties. From what I can see, and again it may just be that I'm not engaging the library correctly, the descriptor validation for package follows similar/same for descriptor validation for resource. In both:
- Validation exists for some items, but not others.
- e.g., name is validated according to frictionless spec
- there is a check that licenses is an array and not empty, but not that the licenses follow the Open definition
- other non-required fields such as version, id don't appear to have validation 

But again some of these I may have missed - so just seeking clarification first, but then if there are fields that don't have validation present, just asking if perhaps it is in the pipline of work or could be considered for future work

**Comment by Stephen-Gates** [comment]
I guess I'd be looking for validation on the `MUST` statements in the specification regardless of the metadata property being required, recommended or optional.

Specifically for `version`,

> a version string identifying the version of the package. It should conform to the Semantic Versioning requirements.

There's a [pattern](http://frictionlessdata.io/specs/patterns/#Data-Package-Version) recommending an approach for versioning but given the spec only requires a `string`, I'd expect the validation to check that if the optional metadata properties `version` exists, it must be a `string`.

It may be useful to identify the `MUST` statements in the [spec ](http://frictionlessdata.io/specs/data-package/#specification)that don't have validation so it is clear what needs to be done.

Here's my attempt:

- [x] Check required properties exist
- [ ] Check the type of each property is correct
- [ ] `name` MUST be lower-case and contain only alphanumeric characters along with ".", "_" or "-" characters
- [ ] the `licenses` object MUST contain a `name` property and/or a `path` property. 
- [ ] the `description` MUST be markdown formatted -- this also allows for simple plain text as plain text is itself valid markdown
- [ ] each `Source` object MUST have a `title` 
- [ ] each `Contributor` object MUST have a `title` property
- [ ] The value of the `image` property MUST be a string pointing to the location of the image. The string must be a url-or-path, that is a fully qualified HTTP address, or a relative POSIX path
- [ ] where a path or url is provided, it is a valid link

**Comment by roll** [comment]
@mattRedBox 
@Stephen-Gates 
The package uses general validation based on JSON Schema profiles e.g. http://frictionlessdata.io/schemas/data-package.json. So even it's not in the code many of checklist above points is covered by the JSON Schema validation. But some properties still requires special case validation like `semver` validation etc.

**Comment by roll** [comment]
CLOSING 
it for now because almost every property having the specs level constraints are validated using JSON Schema - https://frictionlessdata.io/schemas/data-package.json

I suggest to us to open individual issue if we find discrepancies between implemented validation and the specs text.
